version: "3.8"
services:
  broker:
    image: eclipse-mosquitto:2
    container_name: mqtt-broker
    restart: always
    ports:
      - "1883:1883"   # MQTT TCP
      - "9001:9001"   # WebSocket (opsional)
    volumes:
      - ./mosquitto.conf:/mosquitto/config/mosquitto.conf
      - ./passwd:/mosquitto/config/passwd
      - ./acl:/mosquitto/config/acl   
