version: "3.8"
services:
  broker:
    image: eclipse-mosquitto:2
    container_name: mqtt-broker
    ports:
      - "1883:1883"   # MQTT
      - "9001:9001"   # WebSocket (opsional kalau lo mau testing via browser)
    volumes:
      - ./mosquitto.conf:/mosquitto/config/mosquitto.conf
